// <auto-generated />
using MVC_ECD_Start.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace MVC_ECD_Start.Migrations
{
    [DbContext(typeof(StudentDBContext))]
    [Migration("20210715230002_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.8")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MVC_ECD_Start.Models.CollegeData", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("AverageAdmittedSATScores")
                        .HasColumnType("int");

                    b.Property<int>("CumulativeACTMedianScore")
                        .HasColumnType("int");

                    b.Property<string>("EnrolledSttudentSize")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FederalSchoolCode")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InStateTuitionCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OutStateTuitionCost")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OverallAdmissionRate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolCity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SchoolURL")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("CollegesData");
                });
#pragma warning restore 612, 618
        }
    }
}
